### ISSUE TITLE
Missing autoload script/scene files, lack of credits for wav/mp3

### ISSUE THREAD

**Issue by jhlothamer** [Wiggan/GodotTemplate#2]
The following files are referenced as autoloads but are missing:
-SmartQueuefree="*res://pool/smart_queuefree.gd"
-InstancePool="*res://pool/instance_pool.tscn"

As for the wav and mp3 files, I have no idea where they came from, who made them and what license they are under.  I understand that these may have been created by team members, but I would feel more comfortable if that were spelled out in a readme and that it was explicit that such works were licenced under CC0, CC-BY, or some other license.  I guess you could say "MIT" but that seems weird to me.  Just as long as it is spelled out.  Thanks!!!

**Comment by Wiggan** [comment]
Yes there are some broken stuff in the template at the moment! I'll try and push an update soon. As to the music it's just some stuff I made trying to learn ableton. I'll have a look at making them CC0
